### ISSUE TITLE
cant launch example

### ISSUE THREAD

**Issue by KlyukinSA** [vb64/telemulator3#27]
i just repeat README test ([/tests/test/test_readme.py](https://github.com/vb64/telemulator3/blob/main/tests/test/test_readme.py)

here is what i get:
```
Traceback (most recent call last):
  File "/home/stepan/6sem/kpo/test.py", line 35, in <module>
    send_command(chat, '/start', user)
  File "/home/stepan/.local/lib/python3.10/site-packages/telemulator3/__init__.py", line 77, in send_command
    return chat.send(Command(chat, from_user, command, **kwargs))
  File "/home/stepan/.local/lib/python3.10/site-packages/telemulator3/chat/base.py", line 64, in send
    self.creator.api.send_update(
  File "/home/stepan/.local/lib/python3.10/site-packages/telemulator3/api.py", line 192, in send_update
    update = TeleUpdate(
TypeError: Update.__init__() missing 8 required positional arguments: 'message_reaction', 'message_reaction_count', 'removed_chat_boost', 'chat_boost', 'business_connection', 'business_message', 'edited_business_message', and 'deleted_business_messages'
```

**Comment by vb64** [comment]
Most likely you are using the actual latest version of pyTelegramBotAPI.

This project supports pyTelegramBotAPI versions up to 4.11.0 ([see requirements.txt](https://github.com/vb64/telemulator3/blob/main/requirements.txt))

**Comment by vb64** [comment]
The new telemulator3 [version 1.5](https://github.com/vb64/telemulator3/releases/tag/v.1.5) checks for required pyTelegramBotAPI version on install.
